wdb: false
load: false
path: ./weights/
model:
  beta_0: 0.9
  beta_1: 0.999
  lr: 5e-5
  lambda_1: 1000
  lambda_2: 100
  lambda_3: 1
  zf_size: 512
  zt_size: 1024
train:
  batch_size: 16
  num_epochs: 100
  num_steps: 10000
  T: 15
